// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BookingStatus.
const (
	BookingStatusCANCELLED BookingStatus = "CANCELLED"
	BookingStatusCONFIRMED BookingStatus = "CONFIRMED"
)

// Valid indicates whether the value is a known member of the BookingStatus enum.
func (e BookingStatus) Valid() bool {
	switch e {
	case BookingStatusCANCELLED:
		return true
	case BookingStatusCONFIRMED:
		return true
	default:
		return false
	}
}

// Defines values for FlightStatus.
const (
	FlightStatusCANCELLED FlightStatus = "CANCELLED"
	FlightStatusCOMPLETED FlightStatus = "COMPLETED"
	FlightStatusDEPARTED  FlightStatus = "DEPARTED"
	FlightStatusSCHEDULED FlightStatus = "SCHEDULED"
)

// Valid indicates whether the value is a known member of the FlightStatus enum.
func (e FlightStatus) Valid() bool {
	switch e {
	case FlightStatusCANCELLED:
		return true
	case FlightStatusCOMPLETED:
		return true
	case FlightStatusDEPARTED:
		return true
	case FlightStatusSCHEDULED:
		return true
	default:
		return false
	}
}

// Booking defines model for Booking.
type Booking struct {
	CreatedAt      time.Time          `json:"created_at"`
	FlightId       openapi_types.UUID `json:"flight_id"`
	Id             openapi_types.UUID `json:"id"`
	PassengerEmail string             `json:"passenger_email"`
	PassengerName  string             `json:"passenger_name"`
	SeatCount      int                `json:"seat_count"`
	Status         BookingStatus      `json:"status"`
	TotalPrice     int                `json:"total_price"`
	UserId         openapi_types.UUID `json:"user_id"`
}

// BookingStatus defines model for Booking.Status.
type BookingStatus string

// CreateBookingRequest defines model for CreateBookingRequest.
type CreateBookingRequest struct {
	FlightId       openapi_types.UUID `json:"flight_id"`
	PassengerEmail string             `json:"passenger_email"`
	PassengerName  string             `json:"passenger_name"`
	SeatCount      int                `json:"seat_count"`
	UserId         openapi_types.UUID `json:"user_id"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Flight defines model for Flight.
type Flight struct {
	Airline        string             `json:"airline"`
	ArrivalTime    time.Time          `json:"arrival_time"`
	AvailableSeats int                `json:"available_seats"`
	DepartureTime  time.Time          `json:"departure_time"`
	Destination    string             `json:"destination"`
	FlightNumber   string             `json:"flight_number"`
	Id             openapi_types.UUID `json:"id"`
	Origin         string             `json:"origin"`

	// Price Price in minor units (kopecks/cents)
	Price      int          `json:"price"`
	Status     FlightStatus `json:"status"`
	TotalSeats int          `json:"total_seats"`
}

// FlightStatus defines model for Flight.Status.
type FlightStatus string

// ListBookingsParams defines parameters for ListBookings.
type ListBookingsParams struct {
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`
}

// SearchFlightsParams defines parameters for SearchFlights.
type SearchFlightsParams struct {
	Origin      string              `form:"origin" json:"origin"`
	Destination string              `form:"destination" json:"destination"`
	Date        *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// CreateBookingJSONRequestBody defines body for CreateBooking for application/json ContentType.
type CreateBookingJSONRequestBody = CreateBookingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List bookings for a user
	// (GET /bookings)
	ListBookings(ctx echo.Context, params ListBookingsParams) error
	// Create a new booking
	// (POST /bookings)
	CreateBooking(ctx echo.Context) error
	// Get booking by ID
	// (GET /bookings/{id})
	GetBooking(ctx echo.Context, id openapi_types.UUID) error
	// Cancel a booking
	// (POST /bookings/{id}/cancel)
	CancelBooking(ctx echo.Context, id openapi_types.UUID) error
	// Search flights by route and optional date
	// (GET /flights)
	SearchFlights(ctx echo.Context, params SearchFlightsParams) error
	// Get flight by ID
	// (GET /flights/{id})
	GetFlight(ctx echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListBookings converts echo context to params.
func (w *ServerInterfaceWrapper) ListBookings(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBookingsParams
	// ------------- Required query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "user_id", ctx.QueryParams(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBookings(ctx, params)
	return err
}

// CreateBooking converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBooking(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBooking(ctx)
	return err
}

// GetBooking converts echo context to params.
func (w *ServerInterfaceWrapper) GetBooking(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBooking(ctx, id)
	return err
}

// CancelBooking converts echo context to params.
func (w *ServerInterfaceWrapper) CancelBooking(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CancelBooking(ctx, id)
	return err
}

// SearchFlights converts echo context to params.
func (w *ServerInterfaceWrapper) SearchFlights(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchFlightsParams
	// ------------- Required query parameter "origin" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "origin", ctx.QueryParams(), &params.Origin, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter origin: %s", err))
	}

	// ------------- Required query parameter "destination" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "destination", ctx.QueryParams(), &params.Destination, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter destination: %s", err))
	}

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date", ctx.QueryParams(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchFlights(ctx, params)
	return err
}

// GetFlight converts echo context to params.
func (w *ServerInterfaceWrapper) GetFlight(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetFlight(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/bookings", wrapper.ListBookings)
	router.POST(baseURL+"/bookings", wrapper.CreateBooking)
	router.GET(baseURL+"/bookings/:id", wrapper.GetBooking)
	router.POST(baseURL+"/bookings/:id/cancel", wrapper.CancelBooking)
	router.GET(baseURL+"/flights", wrapper.SearchFlights)
	router.GET(baseURL+"/flights/:id", wrapper.GetFlight)

}
